# Generated by Django 3.0.4 on 2020-06-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200, null=True)),
                ('ref_no', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('offer_type', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('reserved_quantity', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.FloatField(null=True)),
                ('sale_price', models.FloatField()),
                ('payment_status', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('SERVICE', 'SERVICE')], default='PRODUCT', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
