# Generated by Django 3.0.4 on 2020-06-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200, null=True)),
                ('expiry_date', models.CharField(max_length=200)),
                ('total', models.FloatField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('ACCEPTED', 'ACCEPTED'), ('CANCELED', 'CANCELED'), ('EXPIRED', 'EXPIRED')], default='NEW', max_length=200, null=True)),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='q_customer', to='contacts.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200, null=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'ACTIVE'), ('PARTIALLY_PAID', 'PARTIALLY_PAID')], default='PARTIALLY_PAID', max_length=200, null=True)),
                ('s_quotation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='s_quotation', to='sales.Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('subtotal', models.FloatField(null=True)),
                ('quantity', models.IntegerField(max_length=200, null=True)),
                ('si_sales', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='si_sales', to='sales.Sales')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200, null=True)),
                ('subtotal', models.FloatField(null=True)),
                ('quantity', models.IntegerField(max_length=200, null=True)),
                ('offer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='offer.Offer')),
                ('qi_quotation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='qi_quotation', to='sales.Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
