# Generated by Django 3.0.4 on 2020-06-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
